=== kdreamer/ISODonosti/src/configuracion/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="configuracion">
		<xsd:complexType>
			<xsd:all>
				<xsd:element name="puertoBD" type="xsd:string" />
				<xsd:element name="driverBD" type="xsd:string" />
				<xsd:element name="userBD" type="xsd:string" />
				<xsd:element name="passBD" type="xsd:string" />
				<xsd:element name="fuenteDatos" type="xsd:string" />
				<xsd:element name="serverBD" type="xsd:string" />
				<xsd:element name="protocoloBD" type="xsd:string" />
				<xsd:element name="serverRMI" type="xsd:string" />
				<xsd:element name="puertoRMI" type="xsd:string" />
				<xsd:element name="servicioRMI" type="xsd:string" />
				<xsd:element name="ficheroReservas" type="xsd:string" />
			</xsd:all>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== kdreamer/ISODonosti/src/configuracion/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuracion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd" >
	<puertoBD>3306</puertoBD>
	<driverBD>com.mysql.jdbc.Driver</driverBD>
	<userBD>root</userBD>
	<passBD>root</passBD>
	<fuenteDatos>cararural2011</fuenteDatos>
	<serverBD>localhost</serverBD>
	<protocoloBD>jdbc:mysql</protocoloBD>
	<serverRMI>localhost</serverRMI>
	<puertoRMI>1099</puertoRMI>
	<servicioRMI>CasaRural2011</servicioRMI>
	<ficheroReservas>numeroReserva.txt</ficheroReservas>
</configuracion>
